[package]
name = "yaum"
version = "0.1.2"
license = "MIT"
description = "Yet Another Units of Measurement"
repository = "https://github.com/bugadani/yaum"
authors = ["DÃ¡niel Buga <bugadani@gmail.com>"]
edition = "2018"

[features]
double_precision = []